Add configurable validation for username, name, and email
mkhorasani/Streamlit-Authenticator pull request #63
Opened 2023-04-28 19:32 UTC by velicanu

Hey @mkhorasani  ,

This PR is an alternative implementation to https://github.com/mkhorasani/Streamlit-Authenticator/pull/52 in order to address https://github.com/mkhorasani/Streamlit-Authenticator/issues/53 .

The reasons I propose this implementation (over https://github.com/mkhorasani/Streamlit-Authenticator/pull/52) are the following:
* allows users to specify their own validators if their requirements differ from the defaults here
* loosen default name validation, since names around the world can have all sorts of characters
* loosen email validation, emails are also hard to validate properly, the best strategy is to actually try to email the provided address and wait for a response
* simpler code change to the existing logic

I tested this out in one of my projects using this library and it seems to work.

2023-04-29 10:32 UTC, mkhorasani commented on streamlit_authenticator/validator.py
> +class Validator:
Please follow the same commenting format as other classes and functions as shown below:

    def _check_credentials(self, inplace: bool=True) -> bool:
        """
        Checks the validity of the entered credentials.
        Parameters
        ----------
        inplace: bool
            Inplace setting, True: authentication status will be stored in session state, 
            False: authentication status will be returned as bool.
        Returns
        -------
        bool
            Validity of entered credentials.
        """

2023-04-29 10:36 UTC, mkhorasani requested changes
Thank you for the changes. Please review the changes/comments and submit them again! Cheers.

2023-04-29 10:55 UTC, velicanu commented
> Thank you for the changes. Please review the changes/comments and submit them again! Cheers.

Done: https://github.com/mkhorasani/Streamlit-Authenticator/pull/63/commits/25fc3c552331d617d87c2c80a113e695eb2f5ef7

By the way did you mean to delete the whole setup file or just revert my change in this commit? https://github.com/mkhorasani/Streamlit-Authenticator/pull/63/commits/3ef4a2cf533a8270c0fc365ac4e1562dee8ca791

2023-04-29 10:59 UTC, mkhorasani commented
> > Thank you for the changes. Please review the changes/comments and submit them again! Cheers.
> 
> Done: [25fc3c5](https://github.com/mkhorasani/Streamlit-Authenticator/commit/25fc3c552331d617d87c2c80a113e695eb2f5ef7)
> 
> By the way did you mean to delete the whole setup file or just revert my change in this commit? [3ef4a2c](https://github.com/mkhorasani/Streamlit-Authenticator/commit/3ef4a2cf533a8270c0fc365ac4e1562dee8ca791)

That was fast! No, I only meant to revert the changes.

2023-04-29 11:05 UTC, mkhorasani approved these changes

2023-04-29 11:05 UTC, merged

2023-04-29 11:06 UTC, mkhorasani commented
Thank you. Pull request merged!

2023-05-17 11:54 UTC, velicanu commented
Sure @mkhorasani !

```
        validator: Validator
            A Validator object that checks the validity of the username, name, and email fields
```

2023-05-17 13:39 UTC, mkhorasani commented
> Sure @mkhorasani !
> 
> ```
>         validator: Validator
>             A Validator object that checks the validity of the username, name, and email fields
> ```

Cheers!